// ═══════════════ PART DATA ═══════════════
const partData = {
  cpu: {
    pc: { tag: 'PROZESSOR', name: 'CPU', color: '#00f5ff',
      desc: 'Die Central Processing Unit ist das Gehirn jedes Computers. Sie führt Milliarden von Berechnungen pro Sekunde aus und koordiniert alle anderen Komponenten.',
      specs: [{l:'Kerne',v:'bis 24C / 32T'},{l:'Takt',v:'bis 6,2 GHz Boost'},{l:'Cache',v:'36MB L3'},{l:'TDP',v:'125–253W'},{l:'Fertigung',v:'TSMC 4nm'}],
      models: ['Core i9-14900K','Ryzen 9 9950X','Core i7-14700K','Ryzen 7 9800X3D'] },
    minipc: { tag: 'MOBILER PROZESSOR', name: 'Mobile CPU', color: '#00ff88',
      desc: 'Mobile CPUs vereinen Leistung mit Energieeffizienz. In Mini-PCs sind oft verlötete Laptop-Chips verbaut, die trotzdem beeindruckende Performance liefern.',
      specs: [{l:'Kerne',v:'bis 24C / 24T'},{l:'Takt',v:'bis 5,6 GHz'},{l:'TDP',v:'28–45W konfigurierbar'},{l:'NPU',v:'48 TOPS'}],
      models: ['Core Ultra 9 185H','Ryzen AI 9 HX 370','Core Ultra 7 155H'] },
    laptop: { tag: 'LAPTOP PROZESSOR', name: 'Mobile CPU HX', color: '#7c3aed',
      desc: 'Gaming-Laptop CPUs der HX-Serie bieten Desktop-nahe Performance bei deutlich höherem Energieverbrauch.',
      specs: [{l:'Kerne',v:'24 Kerne / 32 Threads'},{l:'Takt',v:'5,8 GHz Boost'},{l:'Cache',v:'36MB L3'},{l:'TDP',v:'55–157W'}],
      models: ['Core Ultra 9 275HX','Ryzen 9 9955HX3D'] },
    retro: { tag: 'ARM PROZESSOR', name: 'ARM11 CPU', color: '#ffc800',
      desc: 'Der Nintendo 3DS nutzt einen ARM11 Dual-Core mit 268 MHz — für 2011 absolut ausreichend. Ein Co-Prozessor ARM9 übernimmt Systemaufgaben.',
      specs: [{l:'Architektur',v:'ARM11 MPCore'},{l:'Takt',v:'268 MHz'},{l:'Kerne',v:'2x ARM11 + 1x ARM9'},{l:'RAM',v:'128 MB FCRAM'}],
      models: ['Nintendo 3DS XL','New 3DS XL (804MHz)'] }
  },
  gpu: {
    pc: { tag: 'GRAFIKKARTE', name: 'GPU', color: '#7c3aed',
      desc: 'Die GPU rendert alle visuellen Inhalte und ist für Gaming, 3D-Rendering und KI-Berechnungen zuständig. Moderne GPUs haben tausende von Shader-Kernen.',
      specs: [{l:'CUDA-Kerne',v:'21.760 (RTX 5090)'},{l:'VRAM',v:'32GB GDDR7'},{l:'Bandbreite',v:'1.792 GB/s'},{l:'TDP',v:'575W'},{l:'Ray Tracing',v:'5. Generation'}],
      models: ['RTX 5090','RTX 4090','RTX 4070 Ti','RX 9900 XTX'] },
    minipc: { tag: 'INTEGRIERTE GRAFIK', name: 'iGPU', color: '#00ff88',
      desc: 'Integrierte Grafikeinheiten teilen sich RAM mit der CPU, sind aber für alltägliche Aufgaben und leichtes Gaming absolut ausreichend.',
      specs: [{l:'Einheiten',v:'128 Xe-Kerne'},{l:'Takt',v:'bis 2,35 GHz'},{l:'Leistung',v:'ca. 8,3 TFLOPS'},{l:'Shared RAM',v:'bis 16GB'}],
      models: ['Intel Arc (Core Ultra)','Radeon 890M','Radeon 780M'] },
    laptop: { tag: 'LAPTOP GPU', name: 'RTX 5090 Laptop', color: '#7c3aed',
      desc: 'Laptop-GPUs sind gedrosselte Versionen der Desktop-Varianten, aber dennoch extrem leistungsstark für 1440p und 4K Gaming unterwegs.',
      specs: [{l:'CUDA-Kerne',v:'16.384'},{l:'VRAM',v:'24GB GDDR7'},{l:'TGP',v:'150–250W'},{l:'DLSS',v:'Version 4'}],
      models: ['RTX 5090 Laptop','RTX 5080 Laptop','RTX 4090 Laptop'] }
  },
  ram: { pc: { tag: 'ARBEITSSPEICHER', name: 'DDR5 RAM', color: '#00ff88',
      desc: 'DDR5 RAM ist die aktuelle Generation des Arbeitsspeichers. Er speichert aktive Programme und Daten temporär, damit die CPU schnell darauf zugreifen kann.',
      specs: [{l:'Typ',v:'DDR5-6400'},{l:'Kapazität',v:'bis 192GB'},{l:'Bandbreite',v:'51,2 GB/s'},{l:'Latenz',v:'CL32-38'},{l:'Spannung',v:'1,1V'}],
      models: ['Corsair Dominator Titanium','G.Skill Trident Z5 RGB','Kingston Fury Beast'] } },
  ssd: { pc: { tag: 'NVME SPEICHER', name: 'PCIe Gen 5 SSD', color: '#ff6b35',
      desc: 'NVMe SSDs über PCIe sind die schnellsten verfügbaren Massenspeicher. Gen 5 Modelle erreichen Lesegeschwindigkeiten von über 14 GB/s.',
      specs: [{l:'Interface',v:'PCIe 5.0 x4'},{l:'Lesen',v:'bis 14.700 MB/s'},{l:'Schreiben',v:'bis 12.800 MB/s'},{l:'Formfaktor',v:'M.2 2280'},{l:'Kapazität',v:'bis 4TB'}],
      models: ['Samsung 990 Pro','WD Black SN850X','Seagate FireCuda 530'] } },
  mb: { pc: { tag: 'HAUPTPLATINE', name: 'Mainboard', color: '#ff6496',
      desc: 'Das Mainboard verbindet alle Komponenten miteinander. Es bestimmt, welche CPUs, RAM-Kapazitäten und Erweiterungskarten kompatibel sind.',
      specs: [{l:'Chipset',v:'Z890 / X870E'},{l:'RAM-Slots',v:'4x DDR5'},{l:'PCIe',v:'1x PCIe 5.0 x16'},{l:'M.2 Slots',v:'bis 5x NVMe'},{l:'USB',v:'USB4 40Gbps'}],
      models: ['ASUS ROG Maximus Z890','MSI MEG Z890 ACE','Gigabyte X870E AORUS'] } },
  psu: { pc: { tag: 'NETZTEIL', name: 'PSU', color: '#ffc800',
      desc: 'Das Netzteil wandelt Wechselstrom aus der Steckdose in Gleichstrom für alle Komponenten um. Essenziell für Stabilität und Lebensdauer.',
      specs: [{l:'Wattage',v:'850W–1600W'},{l:'Effizienz',v:'80+ Platinum/Titanium'},{l:'Modularität',v:'Voll modular'},{l:'Standard',v:'ATX 3.1'},{l:'PCIe 16-pin',v:'600W'}],
      models: ['be quiet! Dark Power 13','Corsair HX1500i','Seasonic PRIME TX-1600'] } },
  display: {
    laptop: { tag: 'DISPLAY', name: 'OLED Panel', color: '#7c3aed',
      desc: 'OLED Displays bieten perfektes Schwarz, unbegrenzte Kontraste und extrem schnelle Reaktionszeiten — ideal für Gaming und Content Creation.',
      specs: [{l:'Auflösung',v:'2880×1800 (2.8K)'},{l:'Wiederholrate',v:'240Hz'},{l:'Helligkeit',v:'1000 nit HDR'},{l:'Farbraum',v:'DCI-P3 100%'},{l:'Reaktionszeit',v:'0,2ms'}],
      models: ['Samsung OLED','LG OLED','BOE OLED'] },
    phone: { tag: 'SMARTPHONE DISPLAY', name: 'LTPO AMOLED', color: '#ff6b35',
      desc: 'LTPO AMOLED Displays passen ihre Bildwiederholrate dynamisch von 1Hz bis 120Hz an, um Akku zu sparen ohne auf Flüssigkeit zu verzichten.',
      specs: [{l:'Auflösung',v:'3088×1440 QHD+'},{l:'Wiederholrate',v:'1–120Hz LTPO'},{l:'Helligkeit',v:'2600 nit Peak'},{l:'Schutz',v:'Gorilla Glass Victus 2'}],
      models: ['Samsung Galaxy S25 Ultra','iPhone 16 Pro Max'] },
    vr: { tag: 'VR DISPLAYS', name: 'Dual-LCD', color: '#7c3aed',
      desc: 'VR-Headsets nutzen zwei separate Displays — eines für jedes Auge. Hohe Auflösung und schnelle Bildwiederholrate verhindern Cybersickness.',
      specs: [{l:'Auflösung',v:'2x 2064×2208'},{l:'Wiederholrate',v:'90/120Hz'},{l:'Sichtfeld',v:'110° horizontal'},{l:'Linsentyp',v:'Pancake-Optik'}],
      models: ['Meta Quest 3','Apple Vision Pro','PS VR2'] }
  },
  battery: {
    laptop: { tag: 'AKKU', name: 'LiPo Akku', color: '#7c3aed',
      desc: 'Laptop-Akkus sind aus mehreren Lithium-Polymer-Zellen aufgebaut. Maximale Kapazität nach gesetzlicher Grenze für Lufttransport: 99,9 Wh.',
      specs: [{l:'Kapazität',v:'99,9 Wh'},{l:'Ladegeschwindigkeit',v:'140W USB-C PD'},{l:'Ladezyklen',v:'~500 bis 80%'},{l:'Technologie',v:'Lithium-Polymer'}],
      models: ['ASUS ROG Zephyrus G16','MacBook Pro 16"','Razer Blade 16'] },
    handheld: { tag: 'HANDHELD AKKU', name: 'LiPo Akku', color: '#00f5ff',
      desc: 'Handheld-Akkus müssen Performance und Laufzeit balancieren. Der Steam Deck nutzt einen 50Wh Akku für 2–8 Stunden Gaming je nach Spiel.',
      specs: [{l:'Kapazität',v:'40–50 Wh'},{l:'Laufzeit',v:'2–8 Stunden'},{l:'Ladezeit',v:'~2 Std. mit 45W'}],
      models: ['Steam Deck OLED','Nintendo Switch 2','ROG Ally X'] }
  },
  soc: {
    phone: { tag: 'SYSTEM ON CHIP', name: 'Snapdragon 8 Elite', color: '#ff6b35',
      desc: 'Ein SoC vereint CPU, GPU, Neural Processing Unit, Modem und Memory auf einem einzigen Chip. Das spart Platz und reduziert Energieverbrauch.',
      specs: [{l:'CPU',v:'2x 4,47GHz + 6x 3,53GHz'},{l:'GPU',v:'Adreno 830'},{l:'NPU',v:'45 TOPS'},{l:'Modem',v:'Snapdragon X80 5G'},{l:'Fertigung',v:'TSMC 3nm'}],
      models: ['Snapdragon 8 Elite','Apple A18 Pro','Dimensity 9400'] },
    handheld: { tag: 'CUSTOM CHIP', name: 'Gaming SoC', color: '#00f5ff',
      desc: 'Handheld-Konsolen nutzen speziell angepasste Chips. Nintendo und NVIDIA arbeiten zusammen an custom Tegra-Varianten, AMD liefert APUs für Steam Deck.',
      specs: [{l:'GPU',v:'RDNA 3, 8,6 TFLOPS'},{l:'CPU',v:'Zen 4, 8 Kerne'},{l:'RAM',v:'16GB LPDDR5'},{l:'TDP',v:'5–30W'}],
      models: ['AMD Z1 Extreme (ROG)','NVIDIA Tegra (Switch)','AMD APU (Steam Deck)'] },
    vr: { tag: 'XR PROZESSOR', name: 'Snapdragon XR2 Gen 2', color: '#7c3aed',
      desc: 'VR-Chips müssen gleichzeitig zwei hochauflösende Displays rendern, Tracking berechnen und Hand-Erkennung in Echtzeit betreiben.',
      specs: [{l:'CPU',v:'Kryo, 3,2 GHz'},{l:'GPU',v:'Adreno 740'},{l:'NPU',v:'Hexagon NPU'},{l:'RAM',v:'8GB LPDDR5'}],
      models: ['Meta Quest 3','Meta Quest Pro'] }
  },
  camera: { phone: { tag: 'KAMERASYSTEM', name: 'Multi-Kamera Setup', color: '#ff6b35',
      desc: 'Moderne Smartphones haben komplexe Kamerasysteme mit bis zu 5 Sensoren. Periskop-Objektive ermöglichen optischen Zoom bis 10× ohne Qualitätsverlust.',
      specs: [{l:'Hauptkamera',v:'200MP, f/1.7, OIS'},{l:'Periskop Tele',v:'50MP, 10× optisch'},{l:'Ultraweit',v:'12MP, 120°'},{l:'Frontkamera',v:'12MP Autofokus'},{l:'Video',v:'8K 30fps'}],
      models: ['Samsung Galaxy S25 Ultra','Google Pixel 9 Pro XL'] } },
  modem: { phone: { tag: '5G MODEM', name: 'Snapdragon X80', color: '#ff6b35',
      desc: '5G Modems verbinden Smartphones mit den schnellsten Mobilfunknetzen. mmWave bietet extrem hohe Geschwindigkeiten in Stadtzentren.',
      specs: [{l:'Max. Download',v:'10 Gbit/s'},{l:'Frequenzen',v:'Sub-6GHz + mmWave'},{l:'Wi-Fi',v:'Wi-Fi 7'},{l:'Bluetooth',v:'BT 5.4 LE'}],
      models: ['Snapdragon X80','Apple C1 Modem'] } },
  cooling: {
    minipc: { tag: 'KÜHLSYSTEM', name: 'Miniatur-Kühlung', color: '#00ff88',
      desc: 'Mini-PC Kühlungen sind komplex minimiert. Kupfer-Heatpipes leiten Wärme ab, dünne Lüfter mit hochfrequenten Blättern sorgen für Luftdurchsatz.',
      specs: [{l:'Heatpipes',v:'2–4 Kupferpipes'},{l:'Lüfter',v:'1–2x 40–65mm'},{l:'TDP-Limit',v:'bis 65W'},{l:'Lautstärke',v:'< 30 dB unter Last'}],
      models: ['Intel NUC 14 Pro','ASUS NUC 14 Pro AI','Beelink GTR8 Pro'] },
    handheld: { tag: 'AKTIVE KÜHLUNG', name: 'Handheld Kühlung', color: '#00f5ff',
      desc: 'Handheld-Kühlung muss lautlos und effizient sein. Heatpipes leiten Wärme zum Rand des Geräts, wo ein dünner Lüfter die Luft abführt.',
      specs: [{l:'Lüfter',v:'65mm Dual-Blatt'},{l:'Heatpipes',v:'2x Kupfer'},{l:'Wärmeleitpaste',v:'Flüssigmetall'},{l:'Max Temp',v:'< 80°C unter Last'}],
      models: ['Steam Deck OLED','ROG Ally X','Lenovo Legion Go'] }
  },
  lenses: { vr: { tag: 'OPTIK', name: 'Pancake-Linsen', color: '#7c3aed',
      desc: 'Pancake-Linsen falten den optischen Pfad mehrfach, um ein kompaktes Design zu ermöglichen. Sie bieten schärfere Bilder als ältere Fresnel-Linsen.',
      specs: [{l:'Typ',v:'Pancake (Polarisation)'},{l:'Sichtfeld',v:'110° horizontal'},{l:'Sweet Spot',v:'breiter als Fresnel'},{l:'IPD',v:'53–75mm einstellbar'}],
      models: ['Meta Quest 3','Sony PS VR2','PICO 4'] } },
  tracking: { vr: { tag: 'TRACKING', name: 'Inside-Out Tracking', color: '#7c3aed',
      desc: 'Inside-Out Tracking nutzt Kameras am Headset selbst, um die Position im Raum zu bestimmen. Keine externen Basisstationen nötig.',
      specs: [{l:'Kameras',v:'4x Graustufenkameras'},{l:'Freiheitsgrade',v:'6DoF'},{l:'Hand Tracking',v:'ohne Controller'},{l:'Update Rate',v:'120Hz'}],
      models: ['Meta Quest 3','Microsoft HoloLens 2'] } },
  joycon: { handheld: { tag: 'CONTROLLER', name: 'Joy-Con System', color: '#00f5ff',
      desc: 'Joy-Con sind die abnehmbaren Controller des Nintendo Switch. Hall-Effekt Sticks vermeiden den berüchtigten Stick-Drift der ersten Generation.',
      specs: [{l:'Sticks',v:'Hall-Effekt (Switch 2)'},{l:'Rumble',v:'HD Rumble'},{l:'IR Kamera',v:'Infrarot rechts'},{l:'Verbindung',v:'Magnete + Schiene'}],
      models: ['Nintendo Switch 2 Joy-Con'] } },
  '3d': { retro: { tag: 'AUTOSTEREOSKOPIE', name: 'Glasses-Free 3D', color: '#ffc800',
      desc: 'Der 3DS nutzt einen Parallax-Barrier-Filter vor dem oberen Display. Er blockiert abwechselnd Licht für linkes und rechtes Auge, erzeugt so 3D ohne Brille.',
      specs: [{l:'Technologie',v:'Parallax Barrier'},{l:'Auflösung',v:'800×240 (geteilt)'},{l:'Tiefe',v:'per Schieberegler'},{l:'Sweet Spot',v:'ca. 30cm Abstand'}],
      models: ['Nintendo 3DS XL','New Nintendo 3DS XL'] } },
  dual: { retro: { tag: 'DUAL SCREEN', name: 'Doppeldisplay', color: '#ffc800',
      desc: 'Der 3DS hat zwei Displays: oben ein 3D-Display, unten ein Touchscreen. Beide Bildschirme werden gleichzeitig von der GPU angesteuert.',
      specs: [{l:'Oben',v:'4,88" IPS, 800×240'},{l:'Unten',v:'4,18" TN, 320×240'},{l:'Typ',v:'LCD, keine OLED'},{l:'Helligkeit',v:'5 Stufen'}],
      models: ['New Nintendo 3DS XL'] } },
  streetpass: { retro: { tag: 'WIRELESS', name: 'StreetPass', color: '#ffc800',
      desc: 'StreetPass war eine revolutionäre Funktion: Im Schlafmodus tauschte der 3DS automatisch Daten mit anderen 3DS-Geräten in der Nähe aus.',
      specs: [{l:'WiFi',v:'802.11b/g/n 2,4GHz'},{l:'NFC',v:'amiibo-kompatibel'},{l:'SpotPass',v:'Online-Datenaustausch'},{l:'Reichweite',v:'ca. 30m'}],
      models: ['New Nintendo 3DS XL'] } }
};
